#!/bin/bash
# for auto syntax highlighting

# Show the infos
echo -ne "$ZEN_INFO_TEXT" | zenity --text-info --ok-label="$ZEN_INFO_CONTINUE" --cancel-label="$ZEN_INFO_EXIT" --width=$ZEN_WIDTH_INFO --height=$ZEN_HEIGHT_INFO --font=monospace --title="$SCRIPT_NAME - $ZEN_INFO_TITLE" --window-icon="$WINDOW_ICON"
# 0 Continue, 1 Abort
if [ "$?" = "0" ]; then

	# String of the *.desktop file
	STR="#!/usr/bin/env xdg-open\n\n"
	STR="$STR""[Desktop Entry]\n"
	STR="$STR""Version=1.0\n"

	# Ask for the name
	NAME=$(zenity --entry --text="$ZEN_NAME_TEXT" --title="$SCRIPT_NAME - $ZEN_NAME_TITLE" --width=$ZEN_WIDTH_STANDARD --height=$ZEN_HEIGHT_STANDARD --window-icon="$WINDOW_ICON")
	STR="$STR""Name=""$NAME""\n"

	# Ask for a comment
	COMMENT=$(zenity --entry --text="$ZEN_COMMENT_TEXT" --title="$SCRIPT_NAME - $ZEN_COMMENT_TITLE" --width=$ZEN_WIDTH_STANDARD --height=$ZEN_HEIGHT_STANDARD --window-icon="$WINDOW_ICON")
	STR="$STR""Comment=""$COMMENT""\n"

	# Ask for the mode of icon insertion, then for the icon
	zenity --question --ok-label="$ZEN_ICON_SELECT" --cancel-label="$ZEN_ICON_MANUAL" --text="$ZEN_ICON_TEXT_1" --title="$SCRIPT_NAME - $ZEN_ICON_TITLE" --window-icon="$WINDOW_ICON"
	# 0 Select, 1 Manual
	if [ "$?" = "0" ]; then
		ICON=$(zenity --file-selection --filename="$PWD/0" --file-filter="IMG | $ZEN_ICON_IMG_FILTER" --file-filter="ALL | *" --title="$SCRIPT_NAME - $ZEN_ICON_TITLE" --window-icon="$WINDOW_ICON")
	else
		ICON=$(zenity --entry --entry-text="$PWD/" --text="$ZEN_ICON_TEXT_2" --title="$SCRIPT_NAME  - $ZEN_ICON_TITLE" --width=$ZEN_WIDTH_STANDARD --height=$ZEN_HEIGHT_STANDARD --window-icon="$WINDOW_ICON")
	fi
	STR="$STR""Icon=""$ICON""\n"

	# Ask for the kind of launcher
	zenity --question --ok-label="$ZEN_TYPE_APPLICATION" --cancel-label="$ZEN_TYPE_LINK" --text="$ZEN_TYPE_TEXT" --title="$SCRIPT_NAME - $ZEN_TYPE_TITLE" --width=$ZEN_WIDTH_STANDARD --height=$ZEN_HEIGHT_STANDARD --window-icon="$WINDOW_ICON"
	if [ "$?" = "0" ]; then

		# 0 Application
		STR="$STR""Type=Application\n"

		# Ask for the mode of command insertion, then for the command
		zenity --question --ok-label="$ZEN_COMMAND_SELECT" --cancel-label="$ZEN_COMMAND_MANUAL" --text="$ZEN_COMMAND_TEXT_1" --title="$SCRIPT_NAME - $ZEN_COMMAND_TITLE" --width=$ZEN_WIDTH_STANDARD --height=$ZEN_HEIGHT_STANDARD --window-icon="$WINDOW_ICON"
		# 0 Select, 1 Manual
		if [ "$?" = "0" ]; then
			CMD=$(zenity --file-selection --filename="$PWD/0" --title="$SCRIPT_NAME - $ZEN_COMMAND_TITLE" --window-icon="$WINDOW_ICON")
		else
			PT=$(zenity --entry --entry-text="$PWD/" --text="$ZEN_COMMAND_TEXT_2" --title="$SCRIPT_NAME - $ZEN_COMMAND_TITLE" --width=$ZEN_WIDTH_STANDARD --height=$ZEN_HEIGHT_STANDARD --window-icon="$WINDOW_ICON")
			STR="$STR""Path=""$PT""\n"
			CMD=$(zenity --entry --text="$ZEN_COMMAND_TEXT_3" --title="$SCRIPT_NAME - $ZEN_COMMAND_TITLE" --width=$ZEN_WIDTH_STANDARD --height=$ZEN_HEIGHT_STANDARD --window-icon="$WINDOW_ICON")
		fi
		STR="$STR""Exec=""$CMD""\n"

		# Ask for the kind of execution
		zenity --question --ok-label="$ZEN_TERMINAL_TERMINAL" --cancel-label="$ZEN_TERMINAL_GRAPHIC" --text="$ZEN_TERMINAL_TEXT" --title="$SCRIPT_NAME - $ZEN_TERMINAL_TITLE" --width=$ZEN_WIDTH_STANDARD --height=$ZEN_HEIGHT_STANDARD --window-icon="$WINDOW_ICON"
		# 0 Terminal, 1 Graphic
		if [ "$?" = "0" ]; then
			TERM="true"
		else
			TERM="false"
		fi
		STR="$STR""Terminal=""$TERM""\n"

	else

		# 1 Link
		STR="$STR""Type=Link\n"

		# Ask for the mode of link insertion, then for the link
		zenity --question --ok-label="$ZEN_LINK_SELECT" --cancel-label="$ZEN_LINK_MANUAL" --text="$ZEN_LINK_TEXT_1" --title="$SCRIPT_NAME - $ZEN_LINK_TITLE" --width=$ZEN_WIDTH_STANDARD --height=$ZEN_HEIGHT_STANDARD --window-icon="$WINDOW_ICON"
		# 0 Select, 1 Manual
		if [ "$?" = "0" ]; then
			URL="file://"$(zenity --file-selection --filename="$PWD/0" --title="$SCRIPT_NAME - $ZEN_LINK_TITLE" --window-icon="$WINDOW_ICON")
		else
			URL=$(zenity --entry --entry-text="file://$PWD/" --text="$ZEN_LINK_TEXT_2" --title="$SCRIPT_NAME - $ZEN_LINK_TITLE" --width=$ZEN_WIDTH_STANDARD --height=$ZEN_HEIGHT_STANDARD --window-icon="$WINDOW_ICON")
		fi
		STR="$STR""URL=""$URL""\n"

	fi

	# Show the final result
	EDIT=$(echo -ne "$STR" | zenity --text-info --editable --ok-label="$ZEN_EDIT_CONFIRM" --cancel-label="$ZEN_EDIT_DISCARD" --width=$ZEN_WIDTH_EDIT --height=$ZEN_HEIGHT_EDIT --font=monospace --title="$SCRIPT_NAME - $ZEN_EDIT_TITLE" --window-icon="$WINDOW_ICON")
	# 0 Modify, 1 Continue
	if [ "$?" = "0" ]; then
		STR="$EDIT"
	fi

	# Ask for save file, then save and make executable
	FILE=$(zenity --file-selection --save --confirm-overwrite --filename="$PWD/$NAME.desktop" --file-filter="LAUNCHER | *.desktop" --file-filter="ALL | *" --title="$SCRIPT_NAME - $ZEN_SAVE_TITLE" --window-icon="$WINDOW_ICON")
	# 0 Save, 1 Abort
	if [ "$?" = "0" ]; then
		echo -ne "$STR" > "$FILE"
		chmod +x "$FILE"
	fi

fi
